//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

[assembly: EdmSchemaAttribute()]

namespace MobileGmap
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NGOMobEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NGOMobEntities object using the connection string found in the 'NGOMobEntities' section of the application configuration file.
        /// </summary>
        public NGOMobEntities() : base("name=NGOMobEntities", "NGOMobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NGOMobEntities object.
        /// </summary>
        public NGOMobEntities(string connectionString) : base(connectionString, "NGOMobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NGOMobEntities object.
        /// </summary>
        public NGOMobEntities(EntityConnection connection) : base(connection, "NGOMobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NGODetail> NGODetails
        {
            get
            {
                if ((_NGODetails == null))
                {
                    _NGODetails = base.CreateObjectSet<NGODetail>("NGODetails");
                }
                return _NGODetails;
            }
        }
        private ObjectSet<NGODetail> _NGODetails;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NGODetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNGODetails(NGODetail nGODetail)
        {
            base.AddObject("NGODetails", nGODetail);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NGOMobModel", Name="NGODetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NGODetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NGODetail object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static NGODetail CreateNGODetail(global::System.Int64 id)
        {
            NGODetail nGODetail = new NGODetail();
            nGODetail.ID = id;
            return nGODetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [DisplayName("Location")]
        [Required]
        public global::System.String PlaceName
        {
            get
            {
                return _PlaceName;
            }
            set
            {
                OnPlaceNameChanging(value);
                ReportPropertyChanging("PlaceName");
                _PlaceName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlaceName");
                OnPlaceNameChanged();
            }
        }
        private global::System.String _PlaceName;
        partial void OnPlaceNameChanging(global::System.String value);
        partial void OnPlaceNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Requirements
        {
            get
            {
                return _Requirements;
            }
            set
            {
                OnRequirementsChanging(value);
                ReportPropertyChanging("Requirements");
                _Requirements = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Requirements");
                OnRequirementsChanged();
            }
        }
        private global::System.String _Requirements;
        partial void OnRequirementsChanging(global::System.String value);
        partial void OnRequirementsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [DisplayName("Longitude")]
        public global::System.String GeoLong
        {
            get
            {
                return _GeoLong;
            }
            set
            {
                OnGeoLongChanging(value);
                ReportPropertyChanging("GeoLong");
                _GeoLong = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeoLong");
                OnGeoLongChanged();
            }
        }
        private global::System.String _GeoLong;
        partial void OnGeoLongChanging(global::System.String value);
        partial void OnGeoLongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [DisplayName("Latitude")]
        public global::System.String GeoLat
        {
            get
            {
                return _GeoLat;
            }
            set
            {
                OnGeoLatChanging(value);
                ReportPropertyChanging("GeoLat");
                _GeoLat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeoLat");
                OnGeoLatChanged();
            }
        }
        private global::System.String _GeoLat;
        partial void OnGeoLatChanging(global::System.String value);
        partial void OnGeoLatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Population
        {
            get
            {
                return _Population;
            }
            set
            {
                OnPopulationChanging(value);
                ReportPropertyChanging("Population");
                _Population = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Population");
                OnPopulationChanged();
            }
        }
        private global::System.String _Population;
        partial void OnPopulationChanging(global::System.String value);
        partial void OnPopulationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        [DisplayName("Events Scheduled")]
        public global::System.String EventsScheduled
        {
            get
            {
                return _EventsScheduled;
            }
            set
            {
                OnEventsScheduledChanging(value);
                ReportPropertyChanging("EventsScheduled");
                _EventsScheduled = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventsScheduled");
                OnEventsScheduledChanged();
            }
        }
        private global::System.String _EventsScheduled;
        partial void OnEventsScheduledChanging(global::System.String value);
        partial void OnEventsScheduledChanged();

        #endregion
    
    }

    #endregion
    
}
